// import React, { useState } from "react";
// import useMasters from "../../hooks/useMasters";
// import axiosInstance from "../../api/axiosInstance";
// import jsPDF from "jspdf";
// import autoTable from "jspdf-autotable";
// import * as XLSX from "xlsx";
// import { saveAs } from "file-saver";

// const ConfirmAdmissionReport = () => {
//   const { sessions, standards, sections } = useMasters();
//   const [selectedSession, setSelectedSession] = useState("");
//   const [selectedStandard, setSelectedStandard] = useState("");
//   const [selectedSection, setSelectedSection] = useState("");
//   const [loading, setLoading] = useState(false);

//   const [students, setStudents] = useState([]);
//   const token = localStorage.getItem("token");
//   const user = JSON.parse(localStorage.getItem("user"));

//   const schoolName = user?.school?.schoolName;
//   console.log("school",schoolName);

//   const handleGenerateReport = async () => {
//     try {
//       setLoading(true);

//       const schoolId = localStorage.getItem("schoolId");

//       const response = await axiosInstance.get("/api/admissions/search", {
//         params: {
//           schoolId,
//           academicYear: selectedSession || null,
//           standard: selectedStandard || null,
//           section: selectedSection || null,
//         },
//         headers: {
//           Authorization: `Bearer ${token}`,
//         },
//       });

//       setStudents(response.data);
//     } catch (error) {
//       console.error(error);
//       alert("Failed to generate report");
//     } finally {
//       setLoading(false);
//     }
//   };

//   console.log("Students:", students);

//   //   handle to pdf export
//   const handleExportPDF = () => {
//     const doc = new jsPDF({
//       orientation: "landscape",
//       unit: "mm",
//       format: "a4",
//     });

//     // School Name
//     doc.setFontSize(18);
//     doc.setTextColor(0, 102, 51);
//     doc.text(`${schoolName}`, 148, 15, { align: "center" });

//     // Report Title
//     doc.setFontSize(14);
//     doc.setTextColor(0, 0, 0);
//     doc.text("Confirm Admission Report", 148, 24, { align: "center" });

//     // Filters
//     doc.setFontSize(10);

//     doc.text(`Session : ${selectedSession || "All"}`, 14, 35);

//     doc.text(`Standard : ${selectedStandard || "All"}`, 70, 35);

//     doc.text(`Section : ${selectedSection || "All"}`, 120, 35);

//     doc.text(`Generated : ${new Date().toLocaleDateString()}`, 220, 35);

//     doc.text(`Total Students : ${students.length}`, 220, 42);

//     autoTable(doc, {
//       startY: 48,

//       head: [
//         [
//           "#",
//           "Admission No",
//           "Student Name",
//           "Session",
//           "Class",
//           "Section",
//           "Father",
//           "Mobile",
//           "Gender",
//           "Status",
//         ],
//       ],

//       body: students.map((student, index) => [
//         index + 1,
//         student.admissionNumber,
//         `${student.firstName} ${student.lastName}`,
//         student.academicYear,
//         student.studentClass,
//         student.section,
//         student.fatherName,
//         student.fatherMobile,
//         student.gender,
//         student.status,
//       ]),

//       theme: "grid",

//       styles: {
//         fontSize: 8,
//         cellPadding: 2,
//         halign: "center",
//         valign: "middle",
//       },

//       headStyles: {
//         fillColor: [0, 102, 51],
//         textColor: 255,
//         fontStyle: "bold",
//       },

//       alternateRowStyles: {
//         fillColor: [245, 245, 245],
//       },

//       didDrawPage: function (data) {
//         doc.setFontSize(9);

//         doc.text(
//           `Page ${doc.internal.getNumberOfPages()}`,
//           data.settings.margin.left,
//           doc.internal.pageSize.height - 8,
//         );

//         doc.text(
//           "Generated By School Management System",
//           220,
//           doc.internal.pageSize.height - 8,
//         );
//       },
//     });

//     doc.save("ConfirmAdmissionReport.pdf");
//   };

//   //   handle export to excel
//   const handleExportExcel = () => {
//     if (students.length === 0) {
//       alert("No data available to export.");
//       return;
//     }

//     const excelData = students.map((student, index) => ({
//       "Sl No": index + 1,
//       "Admission No": student.admissionNumber,
//       "Student Name": `${student.firstName} ${student.lastName}`,
//       "Academic Year": student.academicYear,
//       Class: student.studentClass,
//       Section: student.section,
//       Email: student.email,
//       "Aadhar No": student.aadhar,
//       "Father Name": student.fatherName,
//       "Father Mobile": student.fatherMobile,
//       "Mother Name": student.motherName,
//       "Mother Mobile": student.motherMobile,
//       Address: student.address,
//       Gender: student.gender,
//       "Date of Birth": student.dob,
//       Category: student.category,
//       Religion: student.religion,
//       "Admission Date": student.today,
//       Status: student.status,
//     }));

//     // Create Worksheet
//     const worksheet = XLSX.utils.json_to_sheet(excelData);

//     // Column Width
//     worksheet["!cols"] = [
//       { wch: 8 },
//       { wch: 18 },
//       { wch: 25 },
//       { wch: 15 },
//       { wch: 12 },
//       { wch: 10 },
//       { wch: 28 },
//       { wch: 20 },
//       { wch: 25 },
//       { wch: 18 },
//       { wch: 25 },
//       { wch: 18 },
//       { wch: 35 },
//       { wch: 10 },
//       { wch: 15 },
//       { wch: 15 },
//       { wch: 15 },
//       { wch: 18 },
//       { wch: 12 },
//     ];

//     // Workbook
//     const workbook = XLSX.utils.book_new();

//     XLSX.utils.book_append_sheet(workbook, worksheet, "Confirm Admission");

//     // Write Excel
//     const excelBuffer = XLSX.write(workbook, {
//       bookType: "xlsx",
//       type: "array",
//     });

//     const fileData = new Blob([excelBuffer], {
//       type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
//     });

//     saveAs(fileData, "Confirm_Admission_Report.xlsx");
//   };

//   return (
//     <>
//       {/* Header */}
//       <div
//         className="row shadow-lg"
//         style={{
//           backgroundColor: "white",
//           margin: "10px",
//           height: "70px",
//           borderRadius: "5px",
//           padding: "10px",
//           color: "black",
//         }}
//       >
//         <h6>
//           <strong>Confirm Admission Report</strong>
//         </h6>
//         <nav aria-label="breadcrumb py-2">
//           <ol className="breadcrumb">
//             <li className="breadcrumb-item">
//               <a href="/" style={{ textDecoration: "none", color: "black" }}>
//                 Home
//               </a>
//             </li>
//             <li className="breadcrumb-item active">Confirm Admission Report</li>
//           </ol>
//         </nav>
//       </div>

//       {/* search bar */}
//       <div className="ms-2 me-2 mt-3 rounded shadow bg-white">
//         <div className="card">
//           <div className="card-header">Confirm Admission Report</div>
//           <div className="card-body">
//             <div className="row">
//               <div className="col-12 col-md-3">
//                 <label htmlFor="">Sessions:</label>
//                 <select
//                   name=""
//                   id=""
//                   className="form-select"
//                   value={selectedSession}
//                   onChange={(e) => setSelectedSession(e.target.value)}
//                 >
//                   <option value="">Select Session</option>
//                   {sessions.map((session) => (
//                     <option key={session} value={session}>
//                       {session}
//                     </option>
//                   ))}
//                 </select>
//               </div>
//               <div className="col-12 col-md-3">
//                 <label htmlFor="">Standards:</label>
//                 <select
//                   name=""
//                   id=""
//                   className="form-select"
//                   value={selectedStandard}
//                   onChange={(e) => setSelectedStandard(e.target.value)}
//                 >
//                   <option value="">Select Standard</option>
//                   {standards.map((standard) => (
//                     <option key={standard} value={standard}>
//                       {standard}
//                     </option>
//                   ))}
//                 </select>
//               </div>
//               <div className="col-12 col-md-3">
//                 <label htmlFor="">Sections:</label>
//                 <select
//                   name=""
//                   id=""
//                   className="form-select"
//                   value={selectedSection}
//                   onChange={(e) => setSelectedSection(e.target.value)}
//                 >
//                   <option value="">Select Section</option>
//                   {sections.map((section) => (
//                     <option key={section} value={section}>
//                       {section}
//                     </option>
//                   ))}
//                 </select>
//               </div>
//               <div className="col-6 col-md-3">
//                 <button
//                   className="btn btn-primary mt-4"
//                   onClick={handleGenerateReport}
//                   disabled={loading}
//                 >
//                   {loading ? "Loading..." : "Generate Report"}
//                 </button>
//               </div>
//             </div>

//             <div className="row mt-3 g-3 justify-content-end">
//               <div className="col-6 col-md-2">
//                 <button
//                   className="btn btn-danger w-100"
//                   onClick={handleExportPDF}
//                 >
//                   Export PDF
//                 </button>
//               </div>
//               <div className="col-6 col-md-2">
//                 <button
//                   className="btn btn-primary w-100"
//                   onClick={handleExportExcel}
//                 >
//                   Export Excel
//                 </button>
//               </div>
//               <div className="col-6 col-md-2">
//                 <button className="btn btn-warning w-100">Print Report</button>
//               </div>
//             </div>
//           </div>
//         </div>
//       </div>

//       {/* confirm admission report table */}
//       <div className="ms-2 me-2 mt-3 rounded shadow bg-white">
//         <div className="card">
//           <div className="card-header ">Confirm Admission Report Table</div>
//           <div className="card-body table-responsive">
//             <table className="table table-bordered  table-hover">
//               <thead className="table-secondary">
//                 <tr>
//                   <th>#</th>
//                   <th>Student Name</th>
//                   <th>Admission Number</th>
//                   <th>Academic Year</th>
//                   <th>Standard</th>
//                   <th>Section</th>

//                   <th>Email</th>
//                   <th>Aadhar Card</th>
//                   <th>Father's Name</th>
//                   <th>Father's Mobile</th>
//                   <th>Mother's Name</th>
//                   <th>Mother's Mobile</th>
//                   <th>Address</th>
//                   <th>Gender</th>
//                   <th>Date of Birth</th>
//                   <th>Category</th>
//                   <th>Religion</th>
//                   <th>Admission Date</th>
//                   <th>Status</th>
//                 </tr>
//               </thead>
//               <tbody>
//                 {students.map((student, idx) => (
//                   <tr key={student._id}>
//                     <td>{idx + 1}</td>
//                     <td>
//                       {student.firstName} {student.lastName}
//                     </td>
//                     <td>{student.admissionNumber}</td>
//                     <td>{student.academicYear}</td>
//                     <td>{student.studentClass}</td>
//                     <td>{student.student?.section}</td>
//                     <td>{student.email}</td>
//                     <td>{student.aadhar}</td>
//                     <td>{student.fatherName}</td>
//                     <td>{student.fatherMobile}</td>
//                     <td>{student.motherName}</td>
//                     <td>{student.motherMobile}</td>
//                     <td>{student.address}</td>
//                     <td>{student.gender}</td>
//                     <td>{student.dob}</td>
//                     <td>{student.category}</td>
//                     <td>{student.religion}</td>
//                     <td>{student.today}</td>
//                     <td className="badge bg-primary text-white align-items-center">
//                       {student.status}
//                     </td>
//                   </tr>
//                 ))}
//               </tbody>
//             </table>
//           </div>
//         </div>
//       </div>
//     </>
//   );
// };

// export default ConfirmAdmissionReport;

import React, { useState } from "react";
import useMasters from "../../hooks/useMasters";
import axiosInstance from "../../api/axiosInstance";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";
import {
  FaFilePdf,
  FaFileExcel,
  FaPrint,
  FaSearch,
  FaFilter,
  FaUsers,
  FaCheckCircle,
  FaGraduationCap,
} from "react-icons/fa";
import { MdOutlineSchool } from "react-icons/md";

const ConfirmAdmissionReport = () => {
  const { sessions, standards, sections } = useMasters();

  const [selectedSession, setSelectedSession] = useState("");
  const [selectedStandard, setSelectedStandard] = useState("");
  const [selectedSection, setSelectedSection] = useState("");
  const [loading, setLoading] = useState(false);
  const [students, setStudents] = useState([]);

  const token = localStorage.getItem("token");
  const user = JSON.parse(localStorage.getItem("user"));

  const schoolName = user?.school?.schoolName || "School Management System";

  /* ================= GENERATE REPORT ================= */

  const handleGenerateReport = async () => {
    try {
      setLoading(true);

      const schoolId =
        user?.schoolId || localStorage.getItem("schoolId");

      const response = await axiosInstance.get(
        "/api/admissions/search",
        {
          params: {
            schoolId,
            academicYear: selectedSession || null,
            standard: selectedStandard || null,
            section: selectedSection || null,
          },
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      setStudents(response.data || []);
    } catch (error) {
      console.error(error);
      alert("Failed to generate report");
    } finally {
      setLoading(false);
    }
  };

  /* ================= RESET FILTER ================= */

  const handleReset = () => {
    setSelectedSession("");
    setSelectedStandard("");
    setSelectedSection("");
    setStudents([]);
  };

  /* ================= PDF ================= */

  const handleExportPDF = () => {
    if (students.length === 0) {
      alert("No data available to export.");
      return;
    }

    const doc = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });

    doc.setFontSize(18);
    doc.setTextColor(11, 107, 83);
    doc.text(schoolName, 148, 15, {
      align: "center",
    });

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Confirm Admission Report", 148, 24, {
      align: "center",
    });

    doc.setFontSize(9);

    doc.text(
      `Session: ${selectedSession || "All"}`,
      14,
      35
    );

    doc.text(
      `Standard: ${selectedStandard || "All"}`,
      70,
      35
    );

    doc.text(
      `Section: ${selectedSection || "All"}`,
      125,
      35
    );

    doc.text(
      `Generated: ${new Date().toLocaleDateString()}`,
      200,
      35
    );

    doc.text(
      `Total Students: ${students.length}`,
      200,
      42
    );

    autoTable(doc, {
      startY: 48,

      head: [
        [
          "#",
          "Admission No",
          "Student Name",
          "Session",
          "Class",
          "Section",
          "Father",
          "Mobile",
          "Gender",
          "Status",
        ],
      ],

      body: students.map((student, index) => [
        index + 1,
        student.admissionNumber || "-",
        `${student.firstName || ""} ${
          student.lastName || ""
        }`,
        student.academicYear || "-",
        student.studentClass || "-",
        student.section || student.student?.section || "-",
        student.fatherName || "-",
        student.fatherMobile || "-",
        student.gender || "-",
        student.status || "-",
      ]),

      theme: "grid",

      styles: {
        fontSize: 8,
        cellPadding: 2,
        halign: "center",
        valign: "middle",
      },

      headStyles: {
        fillColor: [11, 107, 83],
        textColor: 255,
        fontStyle: "bold",
      },

      alternateRowStyles: {
        fillColor: [245, 248, 247],
      },

      didDrawPage: function (data) {
        doc.setFontSize(8);

        doc.text(
          `Page ${doc.internal.getNumberOfPages()}`,
          data.settings.margin.left,
          doc.internal.pageSize.height - 8
        );

        doc.text(
          "Generated By School Management System",
          200,
          doc.internal.pageSize.height - 8
        );
      },
    });

    doc.save("Confirm_Admission_Report.pdf");
  };

  /* ================= EXCEL ================= */

  const handleExportExcel = () => {
    if (students.length === 0) {
      alert("No data available to export.");
      return;
    }

    const excelData = students.map((student, index) => ({
      "Sl No": index + 1,
      "Admission No": student.admissionNumber || "-",
      "Student Name": `${student.firstName || ""} ${
        student.lastName || ""
      }`,
      "Academic Year": student.academicYear || "-",
      Class: student.studentClass || "-",
      Section:
        student.section ||
        student.student?.section ||
        "-",
      Email: student.email || "-",
      "Aadhar No": student.aadhar || "-",
      "Father Name": student.fatherName || "-",
      "Father Mobile": student.fatherMobile || "-",
      "Mother Name": student.motherName || "-",
      "Mother Mobile": student.motherMobile || "-",
      Address: student.address || "-",
      Gender: student.gender || "-",
      "Date of Birth": student.dob || "-",
      Category: student.category || "-",
      Religion: student.religion || "-",
      "Admission Date": student.today || "-",
      Status: student.status || "-",
    }));

    const worksheet = XLSX.utils.json_to_sheet(excelData);

    worksheet["!cols"] = [
      { wch: 8 },
      { wch: 18 },
      { wch: 25 },
      { wch: 15 },
      { wch: 12 },
      { wch: 10 },
      { wch: 28 },
      { wch: 20 },
      { wch: 25 },
      { wch: 18 },
      { wch: 25 },
      { wch: 18 },
      { wch: 35 },
      { wch: 10 },
      { wch: 15 },
      { wch: 15 },
      { wch: 15 },
      { wch: 18 },
      { wch: 12 },
    ];

    const workbook = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(
      workbook,
      worksheet,
      "Confirm Admission"
    );

    const excelBuffer = XLSX.write(workbook, {
      bookType: "xlsx",
      type: "array",
    });

    const fileData = new Blob([excelBuffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });

    saveAs(
      fileData,
      "Confirm_Admission_Report.xlsx"
    );
  };

  /* ================= PRINT ================= */

  const handlePrint = () => {
    if (students.length === 0) {
      alert("No data available to print.");
      return;
    }

    const printWindow = window.open(
      "",
      "_blank",
      "width=1200,height=800"
    );

    const rows = students
      .map(
        (student, index) => `
        <tr>
          <td>${index + 1}</td>
          <td>${student.firstName || ""} ${
          student.lastName || ""
        }</td>
          <td>${student.admissionNumber || "-"}</td>
          <td>${student.academicYear || "-"}</td>
          <td>${student.studentClass || "-"}</td>
          <td>${
            student.section ||
            student.student?.section ||
            "-"
          }</td>
          <td>${student.fatherName || "-"}</td>
          <td>${student.fatherMobile || "-"}</td>
          <td>${student.gender || "-"}</td>
          <td>${student.status || "-"}</td>
        </tr>
      `
      )
      .join("");

    printWindow.document.write(`
      <html>
        <head>
          <title>Confirm Admission Report</title>

          <style>
            body {
              font-family: Arial, sans-serif;
              padding: 25px;
              color: #222;
            }

            .header {
              text-align: center;
              margin-bottom: 20px;
            }

            .school {
              color: #0b6b53;
              font-size: 22px;
              font-weight: bold;
            }

            .title {
              font-size: 17px;
              font-weight: bold;
              margin-top: 6px;
            }

            .filters {
              display: flex;
              justify-content: space-between;
              margin: 15px 0;
              font-size: 12px;
            }

            table {
              width: 100%;
              border-collapse: collapse;
              font-size: 10px;
            }

            th {
              background: #0b6b53;
              color: white;
              padding: 7px;
              border: 1px solid #ddd;
            }

            td {
              padding: 6px;
              border: 1px solid #ddd;
              text-align: center;
            }

            tr:nth-child(even) {
              background: #f5f8f7;
            }

            .footer {
              margin-top: 20px;
              font-size: 10px;
              text-align: center;
            }
          </style>
        </head>

        <body>

          <div class="header">
            <div class="school">${schoolName}</div>
            <div class="title">
              Confirm Admission Report
            </div>
          </div>

          <div class="filters">
            <span>
              <b>Session:</b>
              ${selectedSession || "All"}
            </span>

            <span>
              <b>Standard:</b>
              ${selectedStandard || "All"}
            </span>

            <span>
              <b>Section:</b>
              ${selectedSection || "All"}
            </span>

            <span>
              <b>Total:</b>
              ${students.length}
            </span>

            <span>
              <b>Generated:</b>
              ${new Date().toLocaleDateString()}
            </span>
          </div>

          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Student Name</th>
                <th>Admission No</th>
                <th>Session</th>
                <th>Class</th>
                <th>Section</th>
                <th>Father Name</th>
                <th>Mobile</th>
                <th>Gender</th>
                <th>Status</th>
              </tr>
            </thead>

            <tbody>
              ${rows}
            </tbody>
          </table>

          <div class="footer">
            Generated By School Management System
          </div>

        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();

    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 300);
  };

  return (
    <>
      {/* ================= HEADER ================= */}

     

      <div className="mx-2 mt-2 mb-3">
        <div
          className="rounded-4 shadow overflow-hidden"
          style={{
            background:
              "linear-gradient(135deg,#ffffff 0%,#f5f9ff 60%,#eaf3ff 100%)",
            border: "1px solid #dbeafe",
          }}
        >
          <div className="p-3 p-md-4">
            <div className="d-flex flex-wrap justify-content-between align-items-center gap-3">
              <div className="d-flex align-items-center gap-3">
                <div
                  className="d-flex align-items-center justify-content-center rounded-3"
                  style={{
                    width: "52px",
                    height: "52px",
                    background: "linear-gradient(135deg,#2563eb,#3b82f6)",
                    color: "#fff",
                    boxShadow: "0 8px 20px rgba(37,99,235,.22)",
                  }}
                >
                  <FaGraduationCap size={27} />
                </div>

                <div>
                  <h5 className="mb-1 fw-bold text-dark">Confirm Admission Report</h5>

                  <div className="text-muted small">
                    Admission &nbsp;/ &nbsp; Confirm Admission Report
                  </div>
                </div>
              </div>

              <div className="d-flex align-items-center gap-2">
                <span
                  className="badge rounded-pill px-3 py-2"
                  style={{
                    backgroundColor: "#eff6ff",
                    color: "#2563eb",
                    border: "1px solid #bfdbfe",
                  }}
                >
                  <MdOutlineSchool className="me-1" />
                  Admission Report
                </span>
              </div>
            </div>
          </div>

          <div
            className="px-4 py-2"
            style={{
              backgroundColor: "rgba(239,246,255,.75)",
              borderTop: "1px solid #e0ecff",
            }}
          >
            <small className="text-muted">
              Home &nbsp;›&nbsp; Admission Report &nbsp;›&nbsp;
              <span className="text-primary fw-semibold">
                Confirm Admission Reports
              </span>
            </small>
          </div>
        </div>
      </div>

      {/* ================= FILTER CARD ================= */}

      <div className="ms-2 me-2 mt-3">
        <div
          className="card border-0 shadow"
          style={{
            borderRadius: "10px",
          }}
        >
          <div
            className="card-header bg-white  border-0 d-flex align-items-center"
            style={{
              // backgroundColor: "#0B6B53",
            
              borderRadius: "10px 10px 0 0",
              padding: "13px 18px",
            }}
          >
            <FaFilter className="me-2 text-primary"  />

            <div>
              <h6 className="mb-0">
                Confirm Admission Report
              </h6>

              <small style={{ opacity: 0.85 }}>
                Filter students and generate admission report
              </small>
            </div>
          </div>

          <div className="card-body p-4">
            <div className="row g-3">
              {/* SESSION */}

              <div className="col-12 col-md-4 col-lg-3">
                <label className="form-label fw-semibold">
                  Session
                </label>

                <select
                  className="form-select"
                  value={selectedSession}
                  onChange={(e) =>
                    setSelectedSession(e.target.value)
                  }
                >
                  <option value="">
                    All Sessions
                  </option>

                  {sessions.map((session) => (
                    <option
                      key={session}
                      value={session}
                    >
                      {session}
                    </option>
                  ))}
                </select>
              </div>

              {/* STANDARD */}

              <div className="col-12 col-md-4 col-lg-3">
                <label className="form-label fw-semibold">
                  Standard
                </label>

                <select
                  className="form-select"
                  value={selectedStandard}
                  onChange={(e) =>
                    setSelectedStandard(e.target.value)
                  }
                >
                  <option value="">
                    All Standards
                  </option>

                  {standards.map((standard) => (
                    <option
                      key={standard}
                      value={standard}
                    >
                      {standard}
                    </option>
                  ))}
                </select>
              </div>

              {/* SECTION */}

              <div className="col-12 col-md-4 col-lg-3">
                <label className="form-label fw-semibold">
                  Section
                </label>

                <select
                  className="form-select"
                  value={selectedSection}
                  onChange={(e) =>
                    setSelectedSection(e.target.value)
                  }
                >
                  <option value="">
                    All Sections
                  </option>

                  {sections.map((section) => (
                    <option
                      key={section}
                      value={section}
                    >
                      {section}
                    </option>
                  ))}
                </select>
              </div>

              {/* SEARCH */}

              <div className="col-12 col-lg-3 d-flex align-items-end gap-2">
                <button
                  className="btn w-100 btn-primary"
                  style={{
                    // backgroundColor: "#0B6B53",
                    color: "white",
                    height: "38px",
                  }}
                  onClick={handleGenerateReport}
                  disabled={loading}
                >
                  <FaSearch className="me-2" />

                  {loading
                    ? "Generating..."
                    : "Generate Report"}
                </button>

                <button
                  className="btn btn-outline-secondary"
                  style={{ height: "38px" }}
                  onClick={handleReset}
                >
                  Reset
                </button>
              </div>
            </div>

            {/* ================= EXPORT BUTTONS ================= */}

            <div className="d-flex justify-content-end flex-wrap gap-2 mt-4 pt-3 border-top">
              <button
                className="btn btn-outline-danger"
                onClick={handleExportPDF}
              >
                <FaFilePdf className="me-2" />
                Export PDF
              </button>

              <button
                className="btn btn-outline-primary"
                onClick={handleExportExcel}
              >
                <FaFileExcel className="me-2" />
                Export Excel
              </button>

              <button
                className="btn btn-outline-warning"
                onClick={handlePrint}
              >
                <FaPrint className="me-2" />
                Print Report
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* ================= SUMMARY ================= */}

      <div className="ms-2 me-2 mt-3">
        <div className="row g-3">
          <div className="col-md-6">
            <div
              className="card border-0 shadow"
              style={{
                borderRadius: "10px",
                borderLeft: "4px solid #0B6B53",
              }}
            >
              <div className="card-body d-flex align-items-center">
                <div
                  className="rounded-circle d-flex bg-primary align-items-center text-white justify-content-center me-3"
                  style={{
                    width: "48px",
                    height: "48px",
                    
                    // color: "#0B6B53",

                  }}
                >
                  <FaUsers size={20} />
                </div>

                <div>
                  <small className="text-muted">
                    Total Confirmed Students
                  </small>

                  <h4
                    className="mb-0 fw-bold text-primary"
                    
                  >
                    {students.length}
                  </h4>
                </div>
              </div>
            </div>
          </div>

          <div className="col-md-6">
            <div
              className="card border-0 shadow"
              style={{
                borderRadius: "10px",
                borderLeft: "4px solid #198754",
              }}
            >
              <div className="card-body d-flex align-items-center">
                <div
                  className="rounded-circle d-flex align-items-center justify-content-center me-3"
                  style={{
                    width: "48px",
                    height: "48px",
                    backgroundColor: "#e9f7ef",
                    color: "#198754",
                  }}
                >
                  <FaCheckCircle size={20} />
                </div>

                <div>
                  <small className="text-muted">
                    Report Status
                  </small>

                  <h6 className="mb-0 fw-bold text-primary">
                    {students.length > 0
                      ? "Report Generated"
                      : "No Report Generated"}
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ================= TABLE ================= */}

      <div className="ms-2 me-2 mt-3 mb-4">
        <div
          className="card border-0 shadow"
          style={{
            borderRadius: "10px",
          }}
        >
          <div
            className="card-header border-0 d-flex justify-content-between align-items-center"
            style={{
              backgroundColor: "#ffffff",
              borderRadius: "10px 10px 0 0",
              padding: "15px 18px",
              borderBottom: "1px solid #eee",
            }}
          >
            <div>
              <h6 className="mb-1 fw-bold">
                Confirm Admission Report Table
              </h6>

              <small className="text-muted">
                Showing confirmed admission details
              </small>
            </div>

            <span
              className="badge"
              style={{
                backgroundColor: "#d4e2ff",
                color: "#0B6B53",
                padding: "8px 12px",
              }}
            >
              {students.length} Students
            </span>
          </div>

          <div className="card-body p-0">
            <div className="table-responsive p-3" style={{maxHeight:"650px",overflow:"auto"}}>
              <table className="table  mb-0 table-middle" style={{minWidth:"1950px"}}>
                <thead
                  style={{
                    position: "sticky",
                    top: 0,
                    zIndex: 2,
                    background: "#f8f9fa",
                  }}
                >
                  <tr style={{
                      borderBottom:
                        "1px solid #dee2e6",
                    }}>
                    <th className="text-center"
                      style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>#</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Student Name</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Admission Number</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Academic Year</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Standard</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Section</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Email</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Aadhar Card</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Father's Name</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Father's Mobile</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Mother's Name</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Mother's Mobile</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Address</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Gender</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Date of Birth</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Category</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Religion</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Admission Date</th>
                    <th style={{
                        width: "70px",
                        padding: "14px 12px",
                        fontSize: "12px",
                        color: "#6c757d",
                        fontWeight: "700",
                      }}>Status</th>
                  </tr>
                </thead>

                <tbody>
                  {loading ? (
                    <tr>
                      <td
                          colSpan="10"
                        className="text-center py-5"
                      >
                        <div
                          className="spinner-border text-primary"
                          style={{
                            width: "2.5rem",
                            height: "2.5rem",
                          }}
                        ></div>

                        <div className="mt-3 text-muted small">
                          Generating report...
                        </div>
                      </td>
                    </tr>
                  ) : students.length > 0 ? (
                    students.map((student, idx) => (
                      <tr
                        key={
                          student.id ||
                          student._id ||
                          student.admissionNumber ||
                          idx
                        }
                      >
                        <td className="text-center fw-semibold">
                          {idx + 1}
                        </td>

                        <td className="fw-semibold">
                          {student.firstName || ""}{" "}
                          {student.lastName || ""}
                        </td>

                        <td>
                          {student.admissionNumber || "-"}
                        </td>

                        <td>
                          {student.academicYear || "-"}
                        </td>

                        <td>
                          {student.studentClass || "-"}
                        </td>

                        <td>
                          {student.section ||
                            student.student?.section ||
                            "-"}
                        </td>

                        <td>
                          {student.email || "-"}
                        </td>

                        <td>
                          {student.aadhar || "-"}
                        </td>

                        <td>
                          {student.fatherName || "-"}
                        </td>

                        <td>
                          {student.fatherMobile || "-"}
                        </td>

                        <td>
                          {student.motherName || "-"}
                        </td>

                        <td>
                          {student.motherMobile || "-"}
                        </td>

                        <td
                          style={{
                            minWidth: "180px",
                          }}
                        >
                          {student.address || "-"}
                        </td>

                        <td>
                          {student.gender || "-"}
                        </td>

                        <td>
                          {student.dob || "-"}
                        </td>

                        <td>
                          {student.category || "-"}
                        </td>

                        <td>
                          {student.religion || "-"}
                        </td>

                        <td>
                          {student.today || "-"}
                        </td>

                        <td>
                          <span
                            className="badge d-inline-flex align-items-center gap-1"
                            style={{
                              backgroundColor: "#e7f5ef",
                              color: "#198754",
                              padding: "7px 10px",
                            }}
                          >
                            <FaCheckCircle size={12} />

                            {student.status || "CONFIRMED"}
                          </span>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td
                        colSpan="19"
                        className="text-center py-5"
                      >
                        <FaUsers
                          size={35}
                          className="text-muted mb-2"
                        />

                        <div className="fw-semibold text-muted">
                          No confirmed admission data found
                        </div>

                        <small className="text-muted">
                          Select filters and click Generate
                          Report.
                        </small>
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ConfirmAdmissionReport;