import React, { useState } from "react";
import useMasters from "../../hooks/useMasters";
import axiosInstance from "../../api/axiosInstance";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

const ConfirmAdmissionReport = () => {
  const { sessions, standards, sections } = useMasters();
  const [selectedSession, setSelectedSession] = useState("");
  const [selectedStandard, setSelectedStandard] = useState("");
  const [selectedSection, setSelectedSection] = useState("");
  const [loading, setLoading] = useState(false);

  const [students, setStudents] = useState([]);
  const token = localStorage.getItem("token");
  const user = JSON.parse(localStorage.getItem("user"));

  const schoolName = user?.school?.schoolName;
  console.log("school",schoolName);

  const handleGenerateReport = async () => {
    try {
      setLoading(true);

      const schoolId = localStorage.getItem("schoolId");

      const response = await axiosInstance.get("/api/admissions/search", {
        params: {
          schoolId,
          academicYear: selectedSession || null,
          standard: selectedStandard || null,
          section: selectedSection || null,
        },
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      setStudents(response.data);
    } catch (error) {
      console.error(error);
      alert("Failed to generate report");
    } finally {
      setLoading(false);
    }
  };

  console.log("Students:", students);

  //   handle to pdf export
  const handleExportPDF = () => {
    const doc = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });

    // School Name
    doc.setFontSize(18);
    doc.setTextColor(0, 102, 51);
    doc.text(`${schoolName}`, 148, 15, { align: "center" });

    // Report Title
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Confirm Admission Report", 148, 24, { align: "center" });

    // Filters
    doc.setFontSize(10);

    doc.text(`Session : ${selectedSession || "All"}`, 14, 35);

    doc.text(`Standard : ${selectedStandard || "All"}`, 70, 35);

    doc.text(`Section : ${selectedSection || "All"}`, 120, 35);

    doc.text(`Generated : ${new Date().toLocaleDateString()}`, 220, 35);

    doc.text(`Total Students : ${students.length}`, 220, 42);

    autoTable(doc, {
      startY: 48,

      head: [
        [
          "#",
          "Admission No",
          "Student Name",
          "Session",
          "Class",
          "Section",
          "Father",
          "Mobile",
          "Gender",
          "Status",
        ],
      ],

      body: students.map((student, index) => [
        index + 1,
        student.admissionNumber,
        `${student.firstName} ${student.lastName}`,
        student.academicYear,
        student.studentClass,
        student.section,
        student.fatherName,
        student.fatherMobile,
        student.gender,
        student.status,
      ]),

      theme: "grid",

      styles: {
        fontSize: 8,
        cellPadding: 2,
        halign: "center",
        valign: "middle",
      },

      headStyles: {
        fillColor: [0, 102, 51],
        textColor: 255,
        fontStyle: "bold",
      },

      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },

      didDrawPage: function (data) {
        doc.setFontSize(9);

        doc.text(
          `Page ${doc.internal.getNumberOfPages()}`,
          data.settings.margin.left,
          doc.internal.pageSize.height - 8,
        );

        doc.text(
          "Generated By School Management System",
          220,
          doc.internal.pageSize.height - 8,
        );
      },
    });

    doc.save("ConfirmAdmissionReport.pdf");
  };

  //   handle export to excel
  const handleExportExcel = () => {
    if (students.length === 0) {
      alert("No data available to export.");
      return;
    }

    const excelData = students.map((student, index) => ({
      "Sl No": index + 1,
      "Admission No": student.admissionNumber,
      "Student Name": `${student.firstName} ${student.lastName}`,
      "Academic Year": student.academicYear,
      Class: student.studentClass,
      Section: student.section,
      Email: student.email,
      "Aadhar No": student.aadhar,
      "Father Name": student.fatherName,
      "Father Mobile": student.fatherMobile,
      "Mother Name": student.motherName,
      "Mother Mobile": student.motherMobile,
      Address: student.address,
      Gender: student.gender,
      "Date of Birth": student.dob,
      Category: student.category,
      Religion: student.religion,
      "Admission Date": student.today,
      Status: student.status,
    }));

    // Create Worksheet
    const worksheet = XLSX.utils.json_to_sheet(excelData);

    // Column Width
    worksheet["!cols"] = [
      { wch: 8 },
      { wch: 18 },
      { wch: 25 },
      { wch: 15 },
      { wch: 12 },
      { wch: 10 },
      { wch: 28 },
      { wch: 20 },
      { wch: 25 },
      { wch: 18 },
      { wch: 25 },
      { wch: 18 },
      { wch: 35 },
      { wch: 10 },
      { wch: 15 },
      { wch: 15 },
      { wch: 15 },
      { wch: 18 },
      { wch: 12 },
    ];

    // Workbook
    const workbook = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(workbook, worksheet, "Confirm Admission");

    // Write Excel
    const excelBuffer = XLSX.write(workbook, {
      bookType: "xlsx",
      type: "array",
    });

    const fileData = new Blob([excelBuffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });

    saveAs(fileData, "Confirm_Admission_Report.xlsx");
  };

  return (
    <>
      {/* Header */}
      <div
        className="row shadow-lg"
        style={{
          backgroundColor: "white",
          margin: "10px",
          height: "70px",
          borderRadius: "5px",
          padding: "10px",
          color: "black",
        }}
      >
        <h6>
          <strong>Confirm Admission Report</strong>
        </h6>
        <nav aria-label="breadcrumb py-2">
          <ol className="breadcrumb">
            <li className="breadcrumb-item">
              <a href="/" style={{ textDecoration: "none", color: "black" }}>
                Home
              </a>
            </li>
            <li className="breadcrumb-item active">Confirm Admission Report</li>
          </ol>
        </nav>
      </div>

      {/* search bar */}
      <div className="ms-2 me-2 mt-3 rounded shadow bg-white">
        <div className="card">
          <div className="card-header">Confirm Admission Report</div>
          <div className="card-body">
            <div className="row">
              <div className="col-12 col-md-3">
                <label htmlFor="">Sessions:</label>
                <select
                  name=""
                  id=""
                  className="form-select"
                  value={selectedSession}
                  onChange={(e) => setSelectedSession(e.target.value)}
                >
                  <option value="">Select Session</option>
                  {sessions.map((session) => (
                    <option key={session} value={session}>
                      {session}
                    </option>
                  ))}
                </select>
              </div>
              <div className="col-12 col-md-3">
                <label htmlFor="">Standards:</label>
                <select
                  name=""
                  id=""
                  className="form-select"
                  value={selectedStandard}
                  onChange={(e) => setSelectedStandard(e.target.value)}
                >
                  <option value="">Select Standard</option>
                  {standards.map((standard) => (
                    <option key={standard} value={standard}>
                      {standard}
                    </option>
                  ))}
                </select>
              </div>
              <div className="col-12 col-md-3">
                <label htmlFor="">Sections:</label>
                <select
                  name=""
                  id=""
                  className="form-select"
                  value={selectedSection}
                  onChange={(e) => setSelectedSection(e.target.value)}
                >
                  <option value="">Select Section</option>
                  {sections.map((section) => (
                    <option key={section} value={section}>
                      {section}
                    </option>
                  ))}
                </select>
              </div>
              <div className="col-6 col-md-3">
                <button
                  className="btn btn-primary mt-4"
                  onClick={handleGenerateReport}
                  disabled={loading}
                >
                  {loading ? "Loading..." : "Generate Report"}
                </button>
              </div>
            </div>

            <div className="row mt-3 g-3 justify-content-end">
              <div className="col-6 col-md-2">
                <button
                  className="btn btn-danger w-100"
                  onClick={handleExportPDF}
                >
                  Export PDF
                </button>
              </div>
              <div className="col-6 col-md-2">
                <button
                  className="btn btn-success w-100"
                  onClick={handleExportExcel}
                >
                  Export Excel
                </button>
              </div>
              <div className="col-6 col-md-2">
                <button className="btn btn-warning w-100">Print Report</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* confirm admission report table */}
      <div className="ms-2 me-2 mt-3 rounded shadow bg-white">
        <div className="card">
          <div className="card-header ">Confirm Admission Report Table</div>
          <div className="card-body table-responsive">
            <table className="table table-bordered  table-hover">
              <thead className="table-secondary">
                <tr>
                  <th>#</th>
                  <th>Student Name</th>
                  <th>Admission Number</th>
                  <th>Academic Year</th>
                  <th>Standard</th>
                  <th>Section</th>

                  <th>Email</th>
                  <th>Aadhar Card</th>
                  <th>Father's Name</th>
                  <th>Father's Mobile</th>
                  <th>Mother's Name</th>
                  <th>Mother's Mobile</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>Date of Birth</th>
                  <th>Category</th>
                  <th>Religion</th>
                  <th>Admission Date</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {students.map((student, idx) => (
                  <tr key={student._id}>
                    <td>{idx + 1}</td>
                    <td>
                      {student.firstName} {student.lastName}
                    </td>
                    <td>{student.admissionNumber}</td>
                    <td>{student.academicYear}</td>
                    <td>{student.studentClass}</td>
                    <td>{student.student?.section}</td>
                    <td>{student.email}</td>
                    <td>{student.aadhar}</td>
                    <td>{student.fatherName}</td>
                    <td>{student.fatherMobile}</td>
                    <td>{student.motherName}</td>
                    <td>{student.motherMobile}</td>
                    <td>{student.address}</td>
                    <td>{student.gender}</td>
                    <td>{student.dob}</td>
                    <td>{student.category}</td>
                    <td>{student.religion}</td>
                    <td>{student.today}</td>
                    <td className="badge bg-success text-white align-items-center">
                      {student.status}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
};

export default ConfirmAdmissionReport;
